---
################################################################################
# _config.yml - GitHub Pages Configuration File                                #
#                                                                              #
# Author: Benedict Winchester                                                  #
# Date Created: 14/04/2023                                                     #
# License: MIT                                                                 #
#                                                                              #
################################################################################

theme: minimal
title: HEATDesalination
description: Website and documentation with updates for HEATDesalination.
