---
name: Mypy

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "mypy==0.982"
          pip install "mypy-extensions==0.4.3"
          pip install types-PyYAML
      - name: Analysing the code with mypy
        run: |
          python -m mypy src/heatdesalination
